import React from "react";
import Hero from "@/components/hero";

import scaleImg from "@/public/scale.jpg";

import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Scale",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <Hero imgUrl={scaleImg} altTxt="Hero" content='Welcome to our Scale'/>
  );
}